<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="DotnetGeminiSDK" Version="1.0.14" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Google.Protobuf" Version="3.32.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.24" />
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="PdfPig" Version="0.1.11-alpha-20250425-47584" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\CVHosting.Shared.Models\CVHosting.Shared.Models.csproj" />
    <ProjectReference Include="..\CVRecognizingService.Domain\CVRecognizingService.Domain.csproj" />
    <ProjectReference Include="..\CVRecognizingService.Infrastructure\CVRecognizingService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
