<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>9657bcdf-4ab4-48c5-9347-8db9860bbd18</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="0.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CVRecognizingService.Application\CVRecognizingService.Application.csproj" />
    <ProjectReference Include="..\CVRecognizingService.Infrastructure\CVRecognizingService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exstensions\" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\src\Shared\Protos\cv.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
