<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>25293cd6-a3ef-47e8-817a-64656ce555aa</UserSecretsId>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProfileService.Application\ProfileService.Application.csproj" />
      <ProjectReference Include="..\ProfileService.Domain\ProfileService.Domain.csproj" />
      <ProjectReference Include="..\ProfileService.Infastructure\ProfileService.Infastructure.csproj" />
    </ItemGroup>

</Project>
