<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProfileService.Domain\ProfileService.Domain.csproj" />
      <ProjectReference Include="..\ProfileService.Infastructure\ProfileService.Infastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTOs\" />
      <Folder Include="Services\" />
      <Folder Include="UseCases\Queries\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.0.1" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="MediatR" Version="13.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.4" />
    </ItemGroup>

</Project>
