version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    container_name: profiledb
    environment:
      POSTGRES_DB: profiles
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5430:5432"
    restart: always
    networks:
      - profiles-web

  profileservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    image: ${DOCKER_REGISTRY-}profileservice
    build:
      context: .
      dockerfile: ProfileService.API/Dockerfile
    container_name: profileservice
    ports:
      - "5100:8080"
      - "5101:8081"
    links:  
      - "postgresdb:pg"
    depends_on: 
      - postgresdb
    networks:
      - profiles-web


networks:
  profiles-web:
    driver: bridge